// Strings for the student and admin dashboards. Merged over ./translations,
// ./siteText and ./uiText; English is the fallback for any missing key.
// {n}, {date}, {title} and {time} are filled in by fill() / countText() in
// ./locale. A `_one` key is the singular form; define it in every language
// that defines the plural, or the English singular shows through.

export const dashText = {
  en: {
    dashCountdownLive: 'Voting is live',
    dashCountdownUpcoming: 'Next election',
    dashCountdownClosesIn: 'Voting closes in',
    dashCountdownOpensIn: 'Voting opens in',
    dashCountdownStarts: 'Starts',
    dashCountdownEnds: 'Ends',
    dashCountdownDays: 'Days',
    dashCountdownHours: 'Hours',
    dashCountdownMinutes: 'Minutes',
    dashCountdownSeconds: 'Seconds',
    dashCountdownDaysShort: '{n} days',
    dashCountdownDaysShort_one: '{n} day',
    dashCountdownAlso: 'Also scheduled',
    dashCountdownVoteNow: 'Vote now',
    dashCountdownView: 'View election',
    dashCountdownVoted: 'You have voted',
    dashCountdownIst: 'All times are Indian Standard Time (IST)',
    // Ledger and notices cards
    dashLedgerStatus: 'Ledger Status',
    dashLedgerVerified: 'Election records verified',
    dashLedgerBroken: 'Tampering detected at block #{n}',
    dashLedgerChecking: 'Verifying ledger…',
    dashBlocksSealed_one: '{n} block sealed',
    dashBlocksSealed: '{n} blocks sealed',
    dashViewLedger: 'View Ledger',
    dashRecentBlocks: 'Recent sealed blocks',
    dashVerified: 'Verified',
    dashGenesis: 'Genesis',
    dashBallot: 'Ballot',
    dashViewAllNotices: 'View All Notices',
    dashNoNotices: 'No notices',
    dashNoNoticesCopy: 'New announcements from the election committee will appear here.',
    dashTickerTitle: "What's New",
    dashTickerLive: 'Running',
    dashTickerUpcoming: 'Upcoming',
    dashTickerOpen: 'Kind attention: {title} is now running — voting closes {date}',
    dashTickerSoon: '{title} opens on {date}',
    dashTickerPause: 'Pause updates',
    dashTickerPlay: 'Play updates',

    // Election rows
    dashVoted: 'Voted',
    dashPositions_one: '{n} position',
    dashPositions: '{n} positions',
    dashVoteNow: 'Vote now',
    dashViewReceipt: 'View receipt',
    dashDetails: 'Details',

    // Student dashboard
    dashBallotsWaiting_one: 'You have {n} ballot waiting. Your vote is private and sealed on the ledger.',
    dashBallotsWaiting: 'You have {n} ballots waiting. Your vote is private and sealed on the ledger.',
    dashAllCaughtUp: 'You are all caught up. New ballots will appear here when voting opens.',
    dashNoDeptYear: 'Department and year not set',
    dashIdentityVerified: 'Identity verified',
    dashVerificationPending: 'Verification pending',
    dashCastYourVote: 'Cast your vote',
    dashCastYourVotes: 'Cast your votes ({n})',
    dashEligibleElections: 'Eligible Elections',
    dashEligibleHint: 'Open, upcoming and closed',
    dashActiveElections: 'Active Elections',
    dashAwaitingVote: '{n} awaiting your vote',
    dashAllVoted: 'All voted',
    dashNoneOpen: 'None open right now',
    dashVotesCast: 'Votes Cast',
    dashReceiptsSaved_one: '{n} receipt saved',
    dashReceiptsSaved: '{n} receipts saved',
    dashNoBallotsYet: 'No ballots cast yet',
    dashUpcomingElections: 'Upcoming Elections',
    dashNextOpens: 'Next opens {date}',
    dashNothingScheduled: 'Nothing scheduled',
    dashWaitingTitle_one: '{n} election is waiting for your vote',
    dashWaitingTitle: '{n} elections are waiting for your vote',
    dashClosesParen: '{title} (closes {date})',
    dashBallotProgress: 'Ballot Progress',
    dashNoActiveBallot: 'No active ballot',
    dashContinueBallot: 'Continue to ballot',
    dashStepRegistered: 'Registered',
    dashRegisteredOn: 'On {date}',
    dashStepIdentity: 'Identity Verified',
    dashAwaitingVerification: 'Awaiting verification by the election office',
    dashStepBallot: 'Ballot Available',
    dashNoBallotOpen: 'No ballot is open for you right now',
    dashOpensOn: 'Opens {date}',
    dashClosesOn: 'Voting closes {date}',
    dashStepVoteCast: 'Vote Cast',
    dashStepReceipt: 'Receipt',
    dashReceiptInReceipts: 'Available in My Receipts',
    dashYourElections: 'Your Elections',
    dashYourElectionsSub: 'Open and upcoming elections you are eligible for',
    dashViewAll: 'View all',
    dashNoActiveElections: 'No active elections',
    dashNoActiveElectionsCopy: 'There are currently no elections available for you.',
    dashViewUpcoming: 'View Upcoming Elections',
    dashLiveResults: 'Live Results',
    dashLiveResultsSub: 'Shown only where the election publishes live results',
    dashViewFullResults: 'View Full Results',
    dashNoResults: 'No results to show yet',
    dashNoResultsCopy: 'Results appear here once voting opens for elections with live results.',
    dashResultsHidden: 'Results for {title} are hidden until voting closes on {date}.',
    dashValidVotes: '{n} valid votes',
    dashNoVerifiedCandidates: 'No verified candidates for this position.',

    // Admin dashboard
    dashOpenForVoting_one: '{n} election is open for voting.',
    dashOpenForVoting: '{n} elections are open for voting.',
    dashNeedsAttention_one: '{n} item needs your attention.',
    dashNeedsAttention: '{n} items need your attention.',
    dashNothingNeedsAttention: 'Nothing needs your attention.',
    dashLedgerBlocks_one: '{n} ledger block',
    dashLedgerBlocks: '{n} ledger blocks',
    dashCreateElection: 'Create election',
    dashPostNotice: 'Post notice',
    dashTotalStudents: 'Total Students',
    dashRegisteredRoll: 'Registered on the roll',
    dashPublishedCount: '{n} published',
    dashCandidates: 'Candidates',
    dashVerifiedCount: '{n} verified',
    dashAcrossPublished: 'Across published elections',
    dashPendingReviews: 'Pending Reviews',
    dashNominationsToVerify: 'Nominations to verify',
    dashAllClear: 'All clear',
    dashNominationsAwaiting_one: '{n} candidate nomination awaiting verification',
    dashNominationsAwaiting: '{n} candidate nominations awaiting verification',
    dashDraftsUnpublished_one: '{n} draft election not yet published',
    dashDraftsUnpublished: '{n} draft elections not yet published',
    dashClosesAt: '{title} closes {date} at {time}',
    dashReview: 'Review',
    dashOpen: 'Open',
    dashView: 'View',
    dashPendingActions: 'Pending Actions',
    dashPendingActionsSub: 'Things that need an election officer',
    dashNoPendingActions: 'No pending actions',
    dashNoPendingActionsCopy: 'All nominations are reviewed and every election is published.',
    dashElectionActivity: 'Election Activity',
    dashElectionActivitySub: 'Elections open for voting now',
    dashManage: 'Manage',
    dashNoOpenElections: 'No elections are open',
    dashNoOpenElectionsCopy: 'Published elections appear here while voting is open.',
    dashColElection: 'Election',
    dashColScope: 'Scope',
    dashColCloses: 'Closes',
    dashColVotes: 'Votes',
    dashColTurnout: 'Turnout',
    dashColActions: 'Actions',
    dashColStatus: 'Status',
    dashColPeriod: 'Voting period',
    dashTurnoutLabel: 'Turnout {n}%',
    dashCandidateVerification: 'Candidate Verification',
    dashPendingReview: '{n} pending review',
    dashNothingWaiting: 'Nothing waiting',
    dashAllReviewed: 'All candidates reviewed',
    dashAllReviewedCopy: 'New nominations will appear here for verification.',
    dashVerify: 'Verify',
    dashReject: 'Reject',
    dashRecentActivity: 'Recent System Activity',
    dashRecentActivitySub: 'Latest changes and sealed ballots',
    dashBallotSealedIn: 'Ballot sealed in block #{n} — {title}',
    dashRecentElections: 'Recent Elections',
    dashRecentElectionsSub: 'The five most recently created elections',
    dashUnknownElection: 'Unknown election',

    backTo: 'Back to {page}',
    settingsLanguageNote: 'Navigation, dashboards and the ballot are translated; some pages remain in English.',
  },

  ta: {
    dashCountdownLive: 'வாக்குப்பதிவு நடைபெறுகிறது',
    dashCountdownUpcoming: 'அடுத்த தேர்தல்',
    dashCountdownClosesIn: 'வாக்குப்பதிவு முடிய இன்னும்',
    dashCountdownOpensIn: 'வாக்குப்பதிவு தொடங்க இன்னும்',
    dashCountdownStarts: 'தொடக்கம்',
    dashCountdownEnds: 'முடிவு',
    dashCountdownDays: 'நாட்கள்',
    dashCountdownHours: 'மணி',
    dashCountdownMinutes: 'நிமிடம்',
    dashCountdownSeconds: 'விநாடி',
    dashCountdownDaysShort: '{n} நாட்கள்',
    dashCountdownDaysShort_one: '{n} நாள்',
    dashCountdownAlso: 'மேலும் திட்டமிடப்பட்டவை',
    dashCountdownVoteNow: 'இப்போது வாக்களிக்கவும்',
    dashCountdownView: 'தேர்தலைப் பார்க்க',
    dashCountdownVoted: 'நீங்கள் வாக்களித்துவிட்டீர்கள்',
    dashCountdownIst: 'அனைத்து நேரங்களும் இந்திய நேரம் (IST)',
    dashLedgerStatus: 'லெட்ஜர் நிலை',
    dashLedgerVerified: 'தேர்தல் பதிவுகள் சரிபார்க்கப்பட்டன',
    dashLedgerBroken: 'பிளாக் #{n} இல் முறைகேடு கண்டறியப்பட்டது',
    dashLedgerChecking: 'லெட்ஜர் சரிபார்க்கப்படுகிறது…',
    dashBlocksSealed_one: '{n} பிளாக் முத்திரையிடப்பட்டது',
    dashBlocksSealed: '{n} பிளாக்குகள் முத்திரையிடப்பட்டன',
    dashViewLedger: 'லெட்ஜரைக் காண்க',
    dashRecentBlocks: 'சமீபத்தில் முத்திரையிடப்பட்ட பிளாக்குகள்',
    dashVerified: 'சரிபார்க்கப்பட்டது',
    dashGenesis: 'தொடக்கம்',
    dashBallot: 'வாக்குச்சீட்டு',
    dashViewAllNotices: 'அனைத்து அறிவிப்புகளையும் காண்க',
    dashNoNotices: 'அறிவிப்புகள் இல்லை',
    dashNoNoticesCopy: 'தேர்தல் குழுவின் புதிய அறிவிப்புகள் இங்கே தோன்றும்.',
    dashTickerTitle: 'புதியவை',
    dashTickerLive: 'நடைபெறுகிறது',
    dashTickerUpcoming: 'விரைவில்',
    dashTickerOpen: 'கவனத்திற்கு: {title} தற்போது நடைபெறுகிறது — வாக்களிப்பு {date} அன்று முடிவடையும்',
    dashTickerSoon: '{title} {date} அன்று தொடங்கும்',
    dashTickerPause: 'புதுப்பிப்புகளை நிறுத்து',
    dashTickerPlay: 'புதுப்பிப்புகளை இயக்கு',

    dashVoted: 'வாக்களித்தீர்கள்',
    dashPositions_one: '{n} பதவி',
    dashPositions: '{n} பதவிகள்',
    dashVoteNow: 'இப்போது வாக்களி',
    dashViewReceipt: 'ரசீதைக் காண்க',
    dashDetails: 'விவரங்கள்',

    dashBallotsWaiting_one: 'உங்களுக்காக {n} வாக்குச்சீட்டு காத்திருக்கிறது. உங்கள் வாக்கு ரகசியமானது, லெட்ஜரில் முத்திரையிடப்படும்.',
    dashBallotsWaiting: 'உங்களுக்காக {n} வாக்குச்சீட்டுகள் காத்திருக்கின்றன. உங்கள் வாக்கு ரகசியமானது, லெட்ஜரில் முத்திரையிடப்படும்.',
    dashAllCaughtUp: 'நீங்கள் அனைத்தையும் முடித்துவிட்டீர்கள். வாக்குப்பதிவு தொடங்கும்போது புதிய வாக்குச்சீட்டுகள் இங்கே தோன்றும்.',
    dashNoDeptYear: 'துறை மற்றும் ஆண்டு அமைக்கப்படவில்லை',
    dashIdentityVerified: 'அடையாளம் சரிபார்க்கப்பட்டது',
    dashVerificationPending: 'சரிபார்ப்பு நிலுவையில் உள்ளது',
    dashCastYourVote: 'உங்கள் வாக்கைச் செலுத்துங்கள்',
    dashCastYourVotes: 'உங்கள் வாக்குகளைச் செலுத்துங்கள் ({n})',
    dashEligibleElections: 'தகுதியான தேர்தல்கள்',
    dashEligibleHint: 'திறந்த, வரவிருக்கும் மற்றும் முடிந்தவை',
    dashActiveElections: 'நடைபெறும் தேர்தல்கள்',
    dashAwaitingVote: '{n} உங்கள் வாக்குக்காகக் காத்திருக்கின்றன',
    dashAllVoted: 'அனைத்திலும் வாக்களித்தீர்கள்',
    dashNoneOpen: 'இப்போது எதுவும் திறக்கப்படவில்லை',
    dashVotesCast: 'செலுத்திய வாக்குகள்',
    dashReceiptsSaved_one: '{n} ரசீது சேமிக்கப்பட்டது',
    dashReceiptsSaved: '{n} ரசீதுகள் சேமிக்கப்பட்டன',
    dashNoBallotsYet: 'இன்னும் வாக்கு செலுத்தவில்லை',
    dashUpcomingElections: 'வரவிருக்கும் தேர்தல்கள்',
    dashNextOpens: 'அடுத்தது {date} அன்று திறக்கும்',
    dashNothingScheduled: 'எதுவும் திட்டமிடப்படவில்லை',
    dashWaitingTitle_one: '{n} தேர்தல் உங்கள் வாக்குக்காகக் காத்திருக்கிறது',
    dashWaitingTitle: '{n} தேர்தல்கள் உங்கள் வாக்குக்காகக் காத்திருக்கின்றன',
    dashClosesParen: '{title} ({date} அன்று முடிகிறது)',
    dashBallotProgress: 'வாக்குச்சீட்டு முன்னேற்றம்',
    dashNoActiveBallot: 'செயலில் உள்ள வாக்குச்சீட்டு இல்லை',
    dashContinueBallot: 'வாக்குச்சீட்டுக்குச் செல்க',
    dashStepRegistered: 'பதிவு செய்யப்பட்டது',
    dashRegisteredOn: '{date} அன்று',
    dashStepIdentity: 'அடையாளம் சரிபார்க்கப்பட்டது',
    dashAwaitingVerification: 'தேர்தல் அலுவலகத்தின் சரிபார்ப்புக்காகக் காத்திருக்கிறது',
    dashStepBallot: 'வாக்குச்சீட்டு கிடைக்கிறது',
    dashNoBallotOpen: 'இப்போது உங்களுக்குத் திறந்த வாக்குச்சீட்டு இல்லை',
    dashOpensOn: '{date} அன்று திறக்கும்',
    dashClosesOn: 'வாக்குப்பதிவு {date} அன்று முடியும்',
    dashStepVoteCast: 'வாக்கு செலுத்தப்பட்டது',
    dashStepReceipt: 'ரசீது',
    dashReceiptInReceipts: 'எனது ரசீதுகளில் கிடைக்கும்',
    dashYourElections: 'உங்கள் தேர்தல்கள்',
    dashYourElectionsSub: 'நீங்கள் தகுதியுள்ள திறந்த மற்றும் வரவிருக்கும் தேர்தல்கள்',
    dashViewAll: 'அனைத்தையும் காண்க',
    dashNoActiveElections: 'நடைபெறும் தேர்தல்கள் இல்லை',
    dashNoActiveElectionsCopy: 'தற்போது உங்களுக்கு எந்தத் தேர்தலும் இல்லை.',
    dashViewUpcoming: 'வரவிருக்கும் தேர்தல்களைக் காண்க',
    dashLiveResults: 'நேரடி முடிவுகள்',
    dashLiveResultsSub: 'நேரடி முடிவுகளை வெளியிடும் தேர்தல்களுக்கு மட்டும் காட்டப்படும்',
    dashViewFullResults: 'முழு முடிவுகளைக் காண்க',
    dashNoResults: 'காட்ட முடிவுகள் இன்னும் இல்லை',
    dashNoResultsCopy: 'நேரடி முடிவுகள் உள்ள தேர்தல்களில் வாக்குப்பதிவு தொடங்கியதும் முடிவுகள் இங்கே தோன்றும்.',
    dashResultsHidden: '{title} முடிவுகள், {date} அன்று வாக்குப்பதிவு முடியும் வரை மறைக்கப்பட்டுள்ளன.',
    dashValidVotes: '{n} செல்லுபடியான வாக்குகள்',
    dashNoVerifiedCandidates: 'இந்தப் பதவிக்குச் சரிபார்க்கப்பட்ட வேட்பாளர்கள் இல்லை.',

    dashOpenForVoting_one: '{n} தேர்தல் வாக்குப்பதிவுக்குத் திறந்துள்ளது.',
    dashOpenForVoting: '{n} தேர்தல்கள் வாக்குப்பதிவுக்குத் திறந்துள்ளன.',
    dashNeedsAttention_one: '{n} விஷயம் உங்கள் கவனத்துக்குக் காத்திருக்கிறது.',
    dashNeedsAttention: '{n} விஷயங்கள் உங்கள் கவனத்துக்குக் காத்திருக்கின்றன.',
    dashNothingNeedsAttention: 'உங்கள் கவனம் தேவைப்படும் எதுவும் இல்லை.',
    dashLedgerBlocks_one: '{n} லெட்ஜர் பிளாக்',
    dashLedgerBlocks: '{n} லெட்ஜர் பிளாக்குகள்',
    dashCreateElection: 'தேர்தலை உருவாக்கு',
    dashPostNotice: 'அறிவிப்பை வெளியிடு',
    dashTotalStudents: 'மொத்த மாணவர்கள்',
    dashRegisteredRoll: 'பட்டியலில் பதிவு செய்யப்பட்டவர்கள்',
    dashPublishedCount: '{n} வெளியிடப்பட்டன',
    dashCandidates: 'வேட்பாளர்கள்',
    dashVerifiedCount: '{n} சரிபார்க்கப்பட்டனர்',
    dashAcrossPublished: 'வெளியிடப்பட்ட அனைத்துத் தேர்தல்களிலும்',
    dashPendingReviews: 'நிலுவையிலுள்ள சரிபார்ப்புகள்',
    dashNominationsToVerify: 'சரிபார்க்க வேண்டிய வேட்புமனுக்கள்',
    dashAllClear: 'எல்லாம் முடிந்தது',
    dashNominationsAwaiting_one: '{n} வேட்புமனு சரிபார்ப்புக்குக் காத்திருக்கிறது',
    dashNominationsAwaiting: '{n} வேட்புமனுக்கள் சரிபார்ப்புக்குக் காத்திருக்கின்றன',
    dashDraftsUnpublished_one: '{n} வரைவுத் தேர்தல் இன்னும் வெளியிடப்படவில்லை',
    dashDraftsUnpublished: '{n} வரைவுத் தேர்தல்கள் இன்னும் வெளியிடப்படவில்லை',
    dashClosesAt: '{title} {date} அன்று {time} மணிக்கு முடிகிறது',
    dashReview: 'சரிபார்',
    dashOpen: 'திற',
    dashView: 'காண்க',
    dashPendingActions: 'நிலுவையிலுள்ள பணிகள்',
    dashPendingActionsSub: 'தேர்தல் அலுவலர் கவனிக்க வேண்டியவை',
    dashNoPendingActions: 'நிலுவையிலுள்ள பணிகள் இல்லை',
    dashNoPendingActionsCopy: 'அனைத்து வேட்புமனுக்களும் சரிபார்க்கப்பட்டன, ஒவ்வொரு தேர்தலும் வெளியிடப்பட்டுள்ளது.',
    dashElectionActivity: 'தேர்தல் செயல்பாடு',
    dashElectionActivitySub: 'தற்போது வாக்குப்பதிவுக்குத் திறந்துள்ள தேர்தல்கள்',
    dashManage: 'நிர்வகி',
    dashNoOpenElections: 'திறந்த தேர்தல்கள் இல்லை',
    dashNoOpenElectionsCopy: 'வாக்குப்பதிவு நடைபெறும்போது வெளியிடப்பட்ட தேர்தல்கள் இங்கே தோன்றும்.',
    dashColElection: 'தேர்தல்',
    dashColScope: 'வரம்பு',
    dashColCloses: 'முடிவு நாள்',
    dashColVotes: 'வாக்குகள்',
    dashColTurnout: 'வாக்குப்பதிவு',
    dashColActions: 'செயல்கள்',
    dashColStatus: 'நிலை',
    dashColPeriod: 'வாக்குப்பதிவு காலம்',
    dashTurnoutLabel: 'வாக்குப்பதிவு {n}%',
    dashCandidateVerification: 'வேட்பாளர் சரிபார்ப்பு',
    dashPendingReview: '{n} சரிபார்ப்புக்கு நிலுவையில்',
    dashNothingWaiting: 'எதுவும் காத்திருக்கவில்லை',
    dashAllReviewed: 'அனைத்து வேட்பாளர்களும் சரிபார்க்கப்பட்டனர்',
    dashAllReviewedCopy: 'புதிய வேட்புமனுக்கள் சரிபார்ப்புக்காக இங்கே தோன்றும்.',
    dashVerify: 'சரிபார்',
    dashReject: 'நிராகரி',
    dashRecentActivity: 'சமீபத்திய செயல்பாடு',
    dashRecentActivitySub: 'சமீபத்திய மாற்றங்கள் மற்றும் முத்திரையிடப்பட்ட வாக்குகள்',
    dashBallotSealedIn: 'பிளாக் #{n} இல் வாக்கு முத்திரையிடப்பட்டது — {title}',
    dashRecentElections: 'சமீபத்திய தேர்தல்கள்',
    dashRecentElectionsSub: 'சமீபத்தில் உருவாக்கப்பட்ட ஐந்து தேர்தல்கள்',
    dashUnknownElection: 'அறியப்படாத தேர்தல்',

    backTo: '{page} பக்கத்திற்குத் திரும்பு',
    settingsLanguageNote: 'வழிசெலுத்தல், டாஷ்போர்டுகள் மற்றும் வாக்குச்சீட்டு மொழிபெயர்க்கப்பட்டுள்ளன; சில பக்கங்கள் ஆங்கிலத்தில் இருக்கும்.',
  },

  hi: {
    dashCountdownLive: 'मतदान जारी है',
    dashCountdownUpcoming: 'अगला चुनाव',
    dashCountdownClosesIn: 'मतदान समाप्त होने में',
    dashCountdownOpensIn: 'मतदान शुरू होने में',
    dashCountdownStarts: 'शुरू',
    dashCountdownEnds: 'समाप्त',
    dashCountdownDays: 'दिन',
    dashCountdownHours: 'घंटे',
    dashCountdownMinutes: 'मिनट',
    dashCountdownSeconds: 'सेकंड',
    dashCountdownDaysShort: '{n} दिन',
    dashCountdownDaysShort_one: '{n} दिन',
    dashCountdownAlso: 'अन्य निर्धारित चुनाव',
    dashCountdownVoteNow: 'अभी मतदान करें',
    dashCountdownView: 'चुनाव देखें',
    dashCountdownVoted: 'आपने मतदान कर दिया है',
    dashCountdownIst: 'सभी समय भारतीय मानक समय (IST) में',
    dashLedgerStatus: 'लेजर स्थिति',
    dashLedgerVerified: 'चुनाव रिकॉर्ड सत्यापित',
    dashLedgerBroken: 'ब्लॉक #{n} पर छेड़छाड़ पाई गई',
    dashLedgerChecking: 'लेजर सत्यापित हो रहा है…',
    dashBlocksSealed_one: '{n} ब्लॉक सील किया गया',
    dashBlocksSealed: '{n} ब्लॉक सील किए गए',
    dashViewLedger: 'लेजर देखें',
    dashRecentBlocks: 'हाल ही में सील किए गए ब्लॉक',
    dashVerified: 'सत्यापित',
    dashGenesis: 'जेनेसिस',
    dashBallot: 'मतपत्र',
    dashViewAllNotices: 'सभी सूचनाएं देखें',
    dashNoNotices: 'कोई सूचना नहीं',
    dashNoNoticesCopy: 'चुनाव समिति की नई घोषणाएं यहां दिखाई देंगी।',
    dashTickerTitle: 'नया क्या है',
    dashTickerLive: 'जारी है',
    dashTickerUpcoming: 'आगामी',
    dashTickerOpen: 'कृपया ध्यान दें: {title} अभी जारी है — मतदान {date} को बंद होगा',
    dashTickerSoon: '{title} {date} को खुलेगा',
    dashTickerPause: 'अपडेट रोकें',
    dashTickerPlay: 'अपडेट चलाएं',

    dashVoted: 'मतदान किया',
    dashPositions_one: '{n} पद',
    dashPositions: '{n} पद',
    dashVoteNow: 'अभी वोट दें',
    dashViewReceipt: 'रसीद देखें',
    dashDetails: 'विवरण',

    dashBallotsWaiting_one: 'आपका {n} मतपत्र प्रतीक्षा में है। आपका वोट गोपनीय है और लेजर पर सील किया जाता है।',
    dashBallotsWaiting: 'आपके {n} मतपत्र प्रतीक्षा में हैं। आपका वोट गोपनीय है और लेजर पर सील किया जाता है।',
    dashAllCaughtUp: 'आपका सब काम पूरा है। मतदान शुरू होने पर नए मतपत्र यहां दिखाई देंगे।',
    dashNoDeptYear: 'विभाग और वर्ष निर्धारित नहीं',
    dashIdentityVerified: 'पहचान सत्यापित',
    dashVerificationPending: 'सत्यापन लंबित',
    dashCastYourVote: 'अपना वोट डालें',
    dashCastYourVotes: 'अपने वोट डालें ({n})',
    dashEligibleElections: 'पात्र चुनाव',
    dashEligibleHint: 'खुले, आगामी और बंद',
    dashActiveElections: 'सक्रिय चुनाव',
    dashAwaitingVote: '{n} आपके वोट की प्रतीक्षा में',
    dashAllVoted: 'सभी में मतदान किया',
    dashNoneOpen: 'अभी कोई खुला नहीं',
    dashVotesCast: 'डाले गए वोट',
    dashReceiptsSaved_one: '{n} रसीद सहेजी गई',
    dashReceiptsSaved: '{n} रसीदें सहेजी गईं',
    dashNoBallotsYet: 'अभी तक कोई वोट नहीं डाला',
    dashUpcomingElections: 'आगामी चुनाव',
    dashNextOpens: 'अगला {date} को खुलेगा',
    dashNothingScheduled: 'कुछ भी निर्धारित नहीं',
    dashWaitingTitle_one: '{n} चुनाव आपके वोट की प्रतीक्षा में है',
    dashWaitingTitle: '{n} चुनाव आपके वोट की प्रतीक्षा में हैं',
    dashClosesParen: '{title} ({date} को बंद)',
    dashBallotProgress: 'मतपत्र प्रगति',
    dashNoActiveBallot: 'कोई सक्रिय मतपत्र नहीं',
    dashContinueBallot: 'मतपत्र पर जाएं',
    dashStepRegistered: 'पंजीकृत',
    dashRegisteredOn: '{date} को',
    dashStepIdentity: 'पहचान सत्यापित',
    dashAwaitingVerification: 'चुनाव कार्यालय द्वारा सत्यापन की प्रतीक्षा',
    dashStepBallot: 'मतपत्र उपलब्ध',
    dashNoBallotOpen: 'अभी आपके लिए कोई मतपत्र खुला नहीं है',
    dashOpensOn: '{date} को खुलेगा',
    dashClosesOn: 'मतदान {date} को बंद होगा',
    dashStepVoteCast: 'वोट डाला गया',
    dashStepReceipt: 'रसीद',
    dashReceiptInReceipts: '"मेरी रसीदें" में उपलब्ध',
    dashYourElections: 'आपके चुनाव',
    dashYourElectionsSub: 'खुले और आगामी चुनाव जिनके लिए आप पात्र हैं',
    dashViewAll: 'सभी देखें',
    dashNoActiveElections: 'कोई सक्रिय चुनाव नहीं',
    dashNoActiveElectionsCopy: 'अभी आपके लिए कोई चुनाव उपलब्ध नहीं है।',
    dashViewUpcoming: 'आगामी चुनाव देखें',
    dashLiveResults: 'लाइव परिणाम',
    dashLiveResultsSub: 'केवल उन चुनावों के लिए जो लाइव परिणाम प्रकाशित करते हैं',
    dashViewFullResults: 'पूरे परिणाम देखें',
    dashNoResults: 'अभी दिखाने के लिए कोई परिणाम नहीं',
    dashNoResultsCopy: 'लाइव परिणाम वाले चुनावों में मतदान शुरू होने पर परिणाम यहां दिखेंगे।',
    dashResultsHidden: '{title} के परिणाम {date} को मतदान बंद होने तक छिपे रहेंगे।',
    dashValidVotes: '{n} वैध वोट',
    dashNoVerifiedCandidates: 'इस पद के लिए कोई सत्यापित उम्मीदवार नहीं।',

    dashOpenForVoting_one: '{n} चुनाव मतदान के लिए खुला है।',
    dashOpenForVoting: '{n} चुनाव मतदान के लिए खुले हैं।',
    dashNeedsAttention_one: '{n} कार्य पर आपका ध्यान चाहिए।',
    dashNeedsAttention: '{n} कार्यों पर आपका ध्यान चाहिए।',
    dashNothingNeedsAttention: 'किसी चीज़ पर आपका ध्यान आवश्यक नहीं है।',
    dashLedgerBlocks_one: '{n} लेजर ब्लॉक',
    dashLedgerBlocks: '{n} लेजर ब्लॉक',
    dashCreateElection: 'चुनाव बनाएं',
    dashPostNotice: 'सूचना प्रकाशित करें',
    dashTotalStudents: 'कुल छात्र',
    dashRegisteredRoll: 'सूची में पंजीकृत',
    dashPublishedCount: '{n} प्रकाशित',
    dashCandidates: 'उम्मीदवार',
    dashVerifiedCount: '{n} सत्यापित',
    dashAcrossPublished: 'सभी प्रकाशित चुनावों में',
    dashPendingReviews: 'लंबित समीक्षाएं',
    dashNominationsToVerify: 'सत्यापन हेतु नामांकन',
    dashAllClear: 'सब ठीक है',
    dashNominationsAwaiting_one: '{n} उम्मीदवार नामांकन सत्यापन की प्रतीक्षा में',
    dashNominationsAwaiting: '{n} उम्मीदवार नामांकन सत्यापन की प्रतीक्षा में',
    dashDraftsUnpublished_one: '{n} ड्राफ्ट चुनाव अभी प्रकाशित नहीं हुआ',
    dashDraftsUnpublished: '{n} ड्राफ्ट चुनाव अभी प्रकाशित नहीं हुए',
    dashClosesAt: '{title} {date} को {time} बजे बंद होगा',
    dashReview: 'समीक्षा करें',
    dashOpen: 'खोलें',
    dashView: 'देखें',
    dashPendingActions: 'लंबित कार्य',
    dashPendingActionsSub: 'जिन पर चुनाव अधिकारी का ध्यान आवश्यक है',
    dashNoPendingActions: 'कोई लंबित कार्य नहीं',
    dashNoPendingActionsCopy: 'सभी नामांकनों की समीक्षा हो चुकी है और हर चुनाव प्रकाशित है।',
    dashElectionActivity: 'चुनाव गतिविधि',
    dashElectionActivitySub: 'अभी मतदान के लिए खुले चुनाव',
    dashManage: 'प्रबंधित करें',
    dashNoOpenElections: 'कोई चुनाव खुला नहीं है',
    dashNoOpenElectionsCopy: 'मतदान खुले रहने पर प्रकाशित चुनाव यहां दिखाई देते हैं।',
    dashColElection: 'चुनाव',
    dashColScope: 'दायरा',
    dashColCloses: 'बंद होगा',
    dashColVotes: 'वोट',
    dashColTurnout: 'मतदान',
    dashColActions: 'कार्रवाई',
    dashColStatus: 'स्थिति',
    dashColPeriod: 'मतदान अवधि',
    dashTurnoutLabel: 'मतदान {n}%',
    dashCandidateVerification: 'उम्मीदवार सत्यापन',
    dashPendingReview: '{n} समीक्षा लंबित',
    dashNothingWaiting: 'कुछ भी प्रतीक्षा में नहीं',
    dashAllReviewed: 'सभी उम्मीदवारों की समीक्षा हो गई',
    dashAllReviewedCopy: 'नए नामांकन सत्यापन के लिए यहां दिखाई देंगे।',
    dashVerify: 'सत्यापित करें',
    dashReject: 'अस्वीकार करें',
    dashRecentActivity: 'हाल की सिस्टम गतिविधि',
    dashRecentActivitySub: 'नवीनतम बदलाव और सील किए गए मतपत्र',
    dashBallotSealedIn: 'ब्लॉक #{n} में मतपत्र सील किया गया — {title}',
    dashRecentElections: 'हाल के चुनाव',
    dashRecentElectionsSub: 'हाल ही में बनाए गए पांच चुनाव',
    dashUnknownElection: 'अज्ञात चुनाव',

    backTo: '{page} पर वापस जाएं',
    settingsLanguageNote: 'नेविगेशन, डैशबोर्ड और मतपत्र अनूदित हैं; कुछ पृष्ठ अंग्रेज़ी में रहेंगे।',
  },
}
