// Copy for the portal shell: header, side navigation, home sections, auth,
// dashboard, ballot flow, results, information pages and the footer.
// Merged over ./translations so the existing ballot, results and receipt
// strings keep working in all three languages.

export const siteText = {
  en: {
    siteBrand: 'College E-Voting System',
    siteBrandShort: 'College E-Voting',
    menu: 'Menu',
    closeMenu: 'Close menu',
    navAboutSite: 'About',
    navServicesSite: 'Services',
    navContact: 'Contact',
    loginRegister: 'Login / Register',
    logout: 'Logout',
    myAccount: 'My account',
    signedInAs: 'Signed in as',
    welcomeUser: 'Welcome',

    menuVoterServices: 'Student services',
    menuElectionInfo: 'Election information',
    dsRegisterRoll: 'Register as a voter',
    dsTrackStatus: 'Check registration status',
    dsDownloadEpic: 'Download voter card',
    dsSearchRoll: 'Search voter roll',
    dsFormsRegistration: 'Registration form',
    dsPollingBooth: 'My voter profile',
    dsRegisterComplaint: 'Raise a query',
    dsVoterEducation: 'How voting works',
    eiCurrentElections: 'Current elections',
    eiPastElections: 'Past elections',
    eiTermHouses: 'Term of office',
    eiElectionResults: 'Election results',
    eiElectoralRoll: 'Voter roll',
    eiModelCode: 'Code of conduct',

    heroTitle: 'Your Vote, Your Voice',
    heroTagline: 'Safe • Transparent • Verifiable',
    heroSubtitle: 'College E-Voting Portal',
    heroCta: 'Get Started',
    heroNote: 'Every ballot is sealed on a tamper-evident ledger the moment you cast it.',

    servicesHeading: 'Our Services',
    servicesSubheading: 'Everything a student voter needs, from registration to the final count.',
    svcRegister: 'Register',
    svcRegisterSub: 'new voter',
    svcLogin: 'Login',
    svcLoginSub: 'existing user',
    svcCandidates: 'View Candidates',
    svcCandidatesSub: 'profiles & manifestos',
    svcCastVote: 'Cast Vote',
    svcCastVoteSub: 'secure ballot',
    svcResults: 'View Results',
    svcResultsSub: 'live verified tally',

    checkHeading: 'Check Your Details',
    checkSubheading: 'Search the voter roll by register number or name.',
    checkPlaceholder: 'Enter register number or name',
    selectState: 'Select State',
    allStates: 'All states',
    search: 'Search',
    checkNoQuery: 'Enter a register number or name to search the roll.',
    checkNoResults: 'No record matched your search. Check the spelling or register as a new voter.',
    checkFound: 'record(s) found',
    colName: 'Name',
    colVoterId: 'Register No.',
    colState: 'State',
    colBooth: 'Polling booth',
    colBallot: 'Ballot status',
    statusVoted: 'Vote recorded',
    statusNotVoted: 'Not yet voted',
    checkPageTitle: 'Search the voter roll',
    checkPageSubtitle: 'Confirm your entry, your department and year, and whether you have voted.',

    aboutProjectTitle: 'About the Project',
    aboutProjectCopy: 'A secure, transparent and tamper-evident e-voting system for college elections, backed by a hash-linked ledger.',
    learnMore: 'Learn More',

    newsHeading: 'Latest Updates / News',
    newsSubtitle: 'Announcements from the election helpdesk.',
    newsPageTitle: 'Updates & news',
    newsPageSubtitle: 'Every notice published for this election, newest first.',
    news1Title: 'Election date announced',
    news1Date: '02 Sep 2026',
    news1Copy: 'Polling for the civic election runs from 7:00 AM to 5:00 PM on 15 October 2026.',
    news2Title: 'New voters can register now',
    news2Date: '08 Sep 2026',
    news2Copy: 'Enrolment is open until 30 September. Register with your EPIC number to reach your ballot.',
    news3Title: 'System maintenance on 20th Sept',
    news3Date: '15 Sep 2026',
    news3Copy: 'The portal is unavailable from 1:00 AM to 3:00 AM while the ledger nodes are upgraded.',
    news4Title: 'Candidate manifestos published',
    news4Date: '18 Sep 2026',
    news4Copy: 'Profiles and declarations for all four candidates are now on the candidates page.',

    loginTitle: 'Login',
    loginSubtitle: 'Sign in with your register number to reach your ballot.',
    usernameLabel: 'Register number / Username',
    passwordLabel: 'Password',
    loginButton: 'Login',
    forgotPassword: 'Forgot Password?',
    or: 'OR',
    noAccount: "Don't have an account?",
    registerLink: 'Register',
    forgotHint: 'Your password is the date of birth you registered with (YYYY-MM-DD). For help, contact the election helpdesk.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    demoCredentials: 'Demo credentials',
    useThisId: 'Use this ID',

    registerTitle: 'Create your voter account',
    registerSubtitle: 'Register once to vote in the college elections you are eligible for.',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'Full Name',
    voterIdField: 'Register number',
    voterIdPlaceholderShort: 'For example 21AD001',
    dobLabel: 'Date of Birth',
    stateLabel: 'State',
    emailLabel: 'Email ID',
    mobileLabel: 'Mobile Number',
    createPassword: 'Password',
    confirmPassword: 'Confirm Password',
    registerButton: 'Register',
    haveAccount: 'Already have an account?',
    loginLink: 'Login',
    registerSuccess: 'Registration complete. You are now signed in.',
    optional: 'optional',

    navDashboard: 'Dashboard',
    dashboardTitle: 'Dashboard',
    dashboardSubtitle: 'Your elections at a glance.',
    dashCardProfile: 'Profile',
    nextElection: 'Next Election',
    electionDateLabel: 'Date',
    electionTimeLabel: 'Time',
    electionDateValue: '15 Oct 2026',
    electionTimeValue: '7:00 AM - 5:00 PM',
    ballotStatusLabel: 'Ballot status',
    dashQuickActions: 'Quick actions',
    dashYourBallot: 'Your ballot',
    dashBallotSub: 'Where you are in the voting journey.',
    stepRegistered: 'Registered on the roll',
    stepSignedIn: 'Identity verified',
    stepBallotCast: 'Ballot sealed on the ledger',
    stepReceiptIssued: 'Receipt available',
    stepDone: 'Done',
    stepNow: 'Now',
    stepNext: 'Next',
    dashLiveResults: 'Live results',
    dashLedgerActivity: 'Ledger activity',

    profileTitle: 'Profile',
    profileSubtitle: 'The details held for you on the college voter roll.',
    downloadEpic: 'Download voter card',
    epicDownloaded: 'Your voter card has been downloaded.',
    accountStatus: 'Account status',
    registeredOn: 'Registered on',
    constituencyLabel: 'Constituency',
    boothLabel: 'Polling booth',
    contactDetails: 'Contact details',
    notProvided: 'Not provided',

    viewDetails: 'View Details',
    candidateProfile: 'Candidate profile',
    manifestoLabel: 'Manifesto',
    ballotNumberLabel: 'Ballot number',
    closeLabel: 'Close',
    voteForThis: 'Vote for this candidate',

    castYourVote: 'Cast Your Vote',
    submitVote: 'Submit Vote',
    selectPrompt: 'Select your candidate, review, then confirm. Your choice is sealed on the ledger.',

    voteCastTitle: 'Your Vote Has Been Cast!',
    voteCastCopy: 'Thank you for taking part in your college elections.',
    goToDashboard: 'Go to Dashboard',

    winnerLabel: 'Winner',
    electionResultsTitle: 'Election Results',

    electionInfoTitle: 'Election information',
    electionInfoSubtitle: 'Schedule, past elections and the rules that govern college elections.',
    currentElectionHeading: 'Current election',
    pastElectionsHeading: 'Past elections',
    termHousesHeading: 'Term of office',
    termHousesCopy: 'Student Council office bearers and representatives serve for one academic year, from the declaration of results until the next year’s elections.',
    modelCodeHeading: 'Code of conduct',
    modelCodeCopy: 'From the announcement of the schedule until results are declared, candidates may not campaign in classrooms or labs, use college resources for campaigning, or approach students at a voting point. Complaints can be raised from the contact page.',
    electoralRollHeading: 'Voter roll',
    electoralRollCopy: 'The roll lists every student eligible to vote. Search your entry, confirm your department and year, and check whether you have voted.',
    archiveGeneral: 'General election',
    archiveAssembly: 'Assembly election',
    archiveBye: 'Bye-election',
    archiveCivic: 'Civic election',
    colElection: 'Election',
    colPeriod: 'Polling period',
    colTurnoutHead: 'Turnout',
    colOutcome: 'Status',
    outcomeDeclared: 'Result declared',
    outcomeOngoing: 'In progress',
    seatsLabel: 'Seats',
    candidatesLabel: 'Candidates',
    constituencyValue: 'Metropolitan Ward 07',

    aboutTitle: 'About the system',
    aboutSubtitle: 'How a cloud-hosted portal and a hash-linked ledger keep college elections honest.',
    aboutLead: 'This portal separates who you are from how you voted. Your identity is checked once at sign-in; the ballot that reaches the ledger carries only a salted digest of your register number, different for every election, so the record proves an eligible student voted without revealing which one.',
    aboutPoint1Title: 'Cloud-hosted access',
    aboutPoint1Copy: 'Students reach the same verified portal from any device, with no software to install.',
    aboutPoint2Title: 'Tamper-evident ledger',
    aboutPoint2Copy:
      'Each ballot block commits to the hash of the one before it, so editing an old vote breaks every block that follows.',
    aboutPoint3Title: 'One student, one ballot',
    aboutPoint3Copy: 'The ledger rejects a second ballot from the same student in the same election, and the roll marks the student as having voted.',
    aboutPoint4Title: 'Open, auditable count',
    aboutPoint4Copy: 'Results are recomputed from the ledger itself, and anyone can re-run the verification pass.',

    contactTitle: 'Contact',
    contactSubtitle: 'Reach the election committee for registration, voting or accessibility support.',
    contactHelpline: 'Election helpdesk',
    contactEmail: 'Email',
    contactAddress: 'Office',
    contactAddressValue: 'Election Committee Office, Administrative Block, Ground Floor',
    contactHours: 'Support hours',
    contactHoursValue: 'Monday to Friday, 9:00 AM – 5:00 PM',
    contactFormTitle: 'Send a message',
    yourName: 'Your name',
    yourEmail: 'Your email',
    yourMessage: 'Message',
    sendMessage: 'Send message',
    messageSent: 'Thank you. Your message has reached the election committee.',

    ledgerStatus: 'Ledger status',
    ledgerVerifiedOk: 'Verified — every block links correctly',
    ledgerBroken: 'Tampering detected in the ledger',
    ledgerChecking: 'Verifying ledger…',
    blocksSealedLabel: 'Blocks sealed',
    ballotsOnLedger: 'Ballots on ledger',
    reVerify: 'Re-verify ledger',

    loginRequiredTitle: 'Sign in to continue',
    loginRequiredCopy: 'Sign in with your register number to continue.',
    goToLogin: 'Go to login',
    alreadyVotedNotice: 'Your ballot for this election is already sealed on the ledger. Thank you for voting.',
    viewReceipt: 'View receipt',
    viewResultsBtn: 'View results',
    sealingBallot: 'Sealing your ballot on the ledger…',
    voteSuccess: 'Your vote has been recorded on the blockchain.',

    footerTagline: 'A secure, ledger-backed election service for college elections.',
    footerQuickLinks: 'Quick Links',
    footerFollow: 'Follow Us',
    socialNote: 'This demonstration portal has no official social accounts yet.',
    footerContactUs: 'Contact Us',
    footerSupport: 'Support',
    footerLegal: 'This is a demonstration portal. Student records and ballots are stored in your browser.',
    footerRights: 'College E-Voting System. All rights reserved.',
  },

  ta: {
    siteBrand: 'கிளவுட் சார்ந்த பிளாக்செயின் மின்-வாக்கு அமைப்பு',
    siteBrandShort: 'பிளாக்செயின் மின்-வாக்கு',
    menu: 'மெனு',
    closeMenu: 'மெனுவை மூடு',
    navAboutSite: 'எங்களைப் பற்றி',
    navServicesSite: 'சேவைகள்',
    navContact: 'தொடர்பு',
    loginRegister: 'உள்நுழைவு / பதிவு',
    logout: 'வெளியேறு',
    myAccount: 'என் கணக்கு',
    signedInAs: 'உள்நுழைந்தவர்',
    welcomeUser: 'வணக்கம்',

    menuVoterServices: 'வாக்காளர் சேவைகள்',
    menuElectionInfo: 'தேர்தல் தகவல்',
    dsRegisterRoll: 'வாக்காளர் பட்டியலில் பதிவு',
    dsTrackStatus: 'விண்ணப்ப நிலையைப் பார்',
    dsDownloadEpic: 'மின்-அடையாள அட்டையைப் பதிவிறக்கு',
    dsSearchRoll: 'வாக்காளர் பட்டியலில் தேடு',
    dsFormsRegistration: 'பதிவுக்கான படிவங்கள்',
    dsPollingBooth: 'உங்கள் வாக்குச் சாவடி',
    dsRegisterComplaint: 'புகார் பதிவு செய்',
    dsVoterEducation: 'வாக்காளர் விழிப்புணர்வு',
    eiCurrentElections: 'நடப்புத் தேர்தல்',
    eiPastElections: 'முந்தைய தேர்தல்கள்',
    eiTermHouses: 'அவைகளின் பதவிக்காலம்',
    eiElectionResults: 'தேர்தல் முடிவுகள்',
    eiElectoralRoll: 'வாக்காளர் பட்டியல்',
    eiModelCode: 'மாதிரி நடத்தை விதிமுறை',

    heroTitle: 'உங்கள் வாக்கு, உங்கள் குரல்',
    heroTagline: 'பாதுகாப்பானது • வெளிப்படையானது • பரவலாக்கப்பட்டது',
    heroSubtitle: 'பிளாக்செயின் இயக்கும் மின்-வாக்கு அமைப்பு',
    heroCta: 'தொடங்குங்கள்',
    heroNote: 'நீங்கள் வாக்களித்த நொடியிலேயே ஒவ்வொரு வாக்கும் மாற்ற முடியாத பதிவேட்டில் பதிவாகிறது.',

    servicesHeading: 'எங்கள் சேவைகள்',
    servicesSubheading: 'பதிவு முதல் இறுதி எண்ணிக்கை வரை வாக்காளருக்குத் தேவையான அனைத்தும்.',
    svcRegister: 'பதிவு',
    svcRegisterSub: 'புதிய வாக்காளர்',
    svcLogin: 'உள்நுழைவு',
    svcLoginSub: 'ஏற்கனவே பதிவானவர்',
    svcCandidates: 'வேட்பாளர்கள்',
    svcCandidatesSub: 'விவரங்கள் & அறிக்கைகள்',
    svcCastVote: 'வாக்களிக்க',
    svcCastVoteSub: 'பாதுகாப்பான வாக்குச்சீட்டு',
    svcResults: 'முடிவுகள்',
    svcResultsSub: 'நேரடி சரிபார்க்கப்பட்ட எண்ணிக்கை',

    checkHeading: 'உங்கள் விவரங்களைச் சரிபார்க்கவும்',
    checkSubheading: 'வாக்காளர் எண் அல்லது பெயர் மூலம் பட்டியலில் தேடுங்கள்.',
    checkPlaceholder: 'வாக்காளர் எண் / பெயரை உள்ளிடவும்',
    selectState: 'மாநிலத்தைத் தேர்வுசெய்க',
    allStates: 'அனைத்து மாநிலங்கள்',
    search: 'தேடு',
    checkNoQuery: 'தேட வாக்காளர் எண் அல்லது பெயரை உள்ளிடவும்.',
    checkNoResults: 'பதிவு எதுவும் கிடைக்கவில்லை. எழுத்துப்பிழையைச் சரிபார்க்கவும் அல்லது புதிதாகப் பதிவு செய்யவும்.',
    checkFound: 'பதிவு(கள்) கிடைத்தன',
    colName: 'பெயர்',
    colVoterId: 'வாக்காளர் எண்',
    colState: 'மாநிலம்',
    colBooth: 'வாக்குச் சாவடி',
    colBallot: 'வாக்கு நிலை',
    statusVoted: 'வாக்கு பதிவாகியது',
    statusNotVoted: 'இன்னும் வாக்களிக்கவில்லை',
    checkPageTitle: 'வாக்காளர் பட்டியலில் தேடுங்கள்',
    checkPageSubtitle: 'உங்கள் பதிவு, வாக்குச் சாவடி மற்றும் வாக்கு எண்ணப்பட்டதா என்பதை உறுதி செய்யுங்கள்.',

    aboutProjectTitle: 'திட்டத்தைப் பற்றி',
    aboutProjectCopy:
      'நேர்மையான தேர்தலை உறுதி செய்ய பிளாக்செயின் தொழில்நுட்பத்தைப் பயன்படுத்தும் பாதுகாப்பான, வெளிப்படையான, மாற்ற முடியாத மின்-வாக்கு அமைப்பு.',
    learnMore: 'மேலும் அறிக',

    newsHeading: 'சமீபத்திய செய்திகள்',
    newsSubtitle: 'தேர்தல் உதவி மையத்தின் அறிவிப்புகள்.',
    newsPageTitle: 'அறிவிப்புகள் & செய்திகள்',
    newsPageSubtitle: 'இந்தத் தேர்தலுக்காக வெளியிடப்பட்ட அனைத்து அறிவிப்புகளும், புதியவை முதலில்.',
    news1Title: 'தேர்தல் தேதி அறிவிக்கப்பட்டது',
    news1Date: '02 செப் 2026',
    news1Copy: '15 அக்டோபர் 2026 அன்று காலை 7:00 முதல் மாலை 5:00 வரை வாக்குப்பதிவு நடைபெறும்.',
    news2Title: 'புதிய வாக்காளர்கள் இப்போது பதிவு செய்யலாம்',
    news2Date: '08 செப் 2026',
    news2Copy: 'செப்டம்பர் 30 வரை பதிவு திறந்திருக்கும். உங்கள் EPIC எண்ணுடன் பதிவு செய்யுங்கள்.',
    news3Title: 'செப்டம்பர் 20 அன்று பராமரிப்பு',
    news3Date: '15 செப் 2026',
    news3Copy: 'பதிவேட்டு கணுக்கள் மேம்படுத்தப்படும் வரை அதிகாலை 1:00 முதல் 3:00 வரை போர்டல் கிடைக்காது.',
    news4Title: 'வேட்பாளர் அறிக்கைகள் வெளியீடு',
    news4Date: '18 செப் 2026',
    news4Copy: 'நான்கு வேட்பாளர்களின் விவரங்களும் அறிக்கைகளும் வேட்பாளர் பக்கத்தில் உள்ளன.',

    loginTitle: 'உள்நுழைவு',
    loginSubtitle: 'உங்கள் வாக்காளர் எண்ணுடன் உள்நுழைந்து வாக்குச்சீட்டை அணுகுங்கள்.',
    usernameLabel: 'வாக்காளர் எண் / பயனர்பெயர்',
    passwordLabel: 'கடவுச்சொல்',
    loginButton: 'உள்நுழை',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    or: 'அல்லது',
    noAccount: 'கணக்கு இல்லையா?',
    registerLink: 'பதிவு செய்க',
    forgotHint: 'நீங்கள் பதிவு செய்த பிறந்த தேதியே (YYYY-MM-DD) கடவுச்சொல். உதவிக்கு 1950 என்ற எண்ணை அழைக்கவும்.',
    showPassword: 'கடவுச்சொல்லைக் காட்டு',
    hidePassword: 'கடவுச்சொல்லை மறை',
    demoCredentials: 'மாதிரி சான்றுகள்',
    useThisId: 'இந்த எண்ணைப் பயன்படுத்து',

    registerTitle: 'உங்கள் கணக்கை உருவாக்குங்கள்',
    registerSubtitle: 'தேர்தலில் பங்கேற்க உங்கள் வாக்காளர் கணக்கை உருவாக்குங்கள்.',
    fullNameLabel: 'முழுப் பெயர்',
    fullNamePlaceholder: 'முழுப் பெயர்',
    voterIdField: 'வாக்காளர் எண்',
    voterIdPlaceholderShort: 'வாக்காளர் எண் (EPIC)',
    dobLabel: 'பிறந்த தேதி',
    stateLabel: 'மாநிலம்',
    emailLabel: 'மின்னஞ்சல்',
    mobileLabel: 'கைபேசி எண்',
    createPassword: 'கடவுச்சொல்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்து',
    registerButton: 'பதிவு செய்',
    haveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    loginLink: 'உள்நுழைவு',
    registerSuccess: 'பதிவு முடிந்தது. நீங்கள் இப்போது உள்நுழைந்துள்ளீர்கள்.',
    optional: 'விருப்பத்திற்குரியது',

    navDashboard: 'முகப்புப் பலகை',
    dashboardTitle: 'முகப்புப் பலகை',
    dashboardSubtitle: 'உங்கள் வாக்காளர் சேவைகள் ஒரே பார்வையில்.',
    dashCardProfile: 'சுயவிவரம்',
    nextElection: 'அடுத்த தேர்தல்',
    electionDateLabel: 'தேதி',
    electionTimeLabel: 'நேரம்',
    electionDateValue: '15 அக் 2026',
    electionTimeValue: 'காலை 7:00 - மாலை 5:00',
    ballotStatusLabel: 'வாக்கு நிலை',
    dashQuickActions: 'விரைவுச் செயல்கள்',
    dashYourBallot: 'உங்கள் வாக்கு',
    dashBallotSub: 'வாக்களிப்புப் பயணத்தில் நீங்கள் எங்கே இருக்கிறீர்கள்.',
    stepRegistered: 'பட்டியலில் பதிவு',
    stepSignedIn: 'அடையாளம் சரிபார்க்கப்பட்டது',
    stepBallotCast: 'வாக்கு பதிவேட்டில் முத்திரையிடப்பட்டது',
    stepReceiptIssued: 'ரசீது கிடைக்கிறது',
    stepDone: 'முடிந்தது',
    stepNow: 'இப்போது',
    stepNext: 'அடுத்து',
    dashLiveResults: 'நேரடி முடிவுகள்',
    dashLedgerActivity: 'பதிவேட்டு நடவடிக்கை',

    profileTitle: 'சுயவிவரம்',
    profileSubtitle: 'வாக்காளர் பட்டியலில் உங்களுக்காக உள்ள விவரங்கள்.',
    downloadEpic: 'மின்-அடையாள அட்டையைப் பதிவிறக்கு',
    epicDownloaded: 'உங்கள் மின்-அடையாள அட்டை பதிவிறக்கப்பட்டது.',
    accountStatus: 'கணக்கு நிலை',
    registeredOn: 'பதிவு செய்த நாள்',
    constituencyLabel: 'தொகுதி',
    boothLabel: 'வாக்குச் சாவடி',
    contactDetails: 'தொடர்பு விவரங்கள்',
    notProvided: 'வழங்கப்படவில்லை',

    viewDetails: 'விவரங்களைப் பார்',
    candidateProfile: 'வேட்பாளர் விவரம்',
    manifestoLabel: 'தேர்தல் அறிக்கை',
    ballotNumberLabel: 'வாக்குச்சீட்டு எண்',
    closeLabel: 'மூடு',
    voteForThis: 'இந்த வேட்பாளருக்கு வாக்களி',

    castYourVote: 'உங்கள் வாக்கைப் பதிவு செய்யுங்கள்',
    submitVote: 'வாக்கைச் சமர்ப்பி',
    selectPrompt: 'ஒரு வேட்பாளரைத் தேர்ந்தெடுத்து சமர்ப்பிக்கவும். உங்கள் தேர்வு பதிவேட்டில் முத்திரையிடப்படும்.',

    voteCastTitle: 'உங்கள் வாக்கு பதிவாகிவிட்டது!',
    voteCastCopy: 'ஜனநாயகச் செயல்பாட்டில் பங்கேற்றதற்கு நன்றி.',
    goToDashboard: 'முகப்புப் பலகைக்குச் செல்',

    winnerLabel: 'வெற்றியாளர்',
    electionResultsTitle: 'தேர்தல் முடிவுகள்',

    electionInfoTitle: 'தேர்தல் தகவல்',
    electionInfoSubtitle: 'அட்டவணை, பழைய பதிவுகள் மற்றும் இந்தத் தேர்தலை ஆளும் விதிகள்.',
    currentElectionHeading: 'நடப்புத் தேர்தல்',
    pastElectionsHeading: 'முந்தைய தேர்தல்கள்',
    termHousesHeading: 'அவைகளின் பதவிக்காலம்',
    termHousesCopy:
      'தேர்ந்தெடுக்கப்பட்ட அவை அதன் முதல் கூட்டத்திலிருந்து ஐந்தாண்டுகள் பணியாற்றும். நடப்புக் காலம் 12 நவம்பர் 2021-இல் தொடங்கி 11 நவம்பர் 2026-இல் முடிகிறது.',
    modelCodeHeading: 'மாதிரி நடத்தை விதிமுறை',
    modelCodeCopy:
      'அட்டவணை அறிவிக்கப்பட்ட நாள் முதல் முடிவு அறிவிக்கப்படும் வரை, வேட்பாளர்கள் பொதுப் பணத்தைப் பிரச்சாரத்திற்குப் பயன்படுத்தவோ, புதிய பொதுப் பணிகளை அறிவிக்கவோ, வாக்குச் சாவடியில் வாக்காளரை அணுகவோ கூடாது. புகார்களைத் தொடர்பு பக்கத்தில் பதிவு செய்யலாம்.',
    electoralRollHeading: 'வாக்காளர் பட்டியல்',
    electoralRollCopy:
      'இந்தத் தேர்தலில் வாக்களிக்கத் தகுதியுடையவர்களின் பட்டியலே இது. உங்கள் பதிவைத் தேடி, வாக்குச் சாவடியை உறுதி செய்து, உங்கள் வாக்கு எண்ணப்பட்டதா எனப் பாருங்கள்.',
    archiveGeneral: 'பொதுத் தேர்தல்',
    archiveAssembly: 'சட்டமன்றத் தேர்தல்',
    archiveBye: 'இடைத்தேர்தல்',
    archiveCivic: 'உள்ளாட்சித் தேர்தல்',
    colElection: 'தேர்தல்',
    colPeriod: 'வாக்குப்பதிவு காலம்',
    colTurnoutHead: 'வாக்குப்பதிவு சதவீதம்',
    colOutcome: 'நிலை',
    outcomeDeclared: 'முடிவு அறிவிக்கப்பட்டது',
    outcomeOngoing: 'நடைபெற்று வருகிறது',
    seatsLabel: 'இடங்கள்',
    candidatesLabel: 'வேட்பாளர்கள்',
    constituencyValue: 'மாநகர வார்டு 07',

    aboutTitle: 'அமைப்பைப் பற்றி',
    aboutSubtitle: 'கிளவுட் போர்டலும் பிளாக்செயின் பதிவேடும் தேர்தலை நேர்மையாக வைத்திருக்கும் விதம்.',
    aboutLead:
      'நீங்கள் யார் என்பதையும் எப்படி வாக்களித்தீர்கள் என்பதையும் இந்த போர்டல் தனித்தனியாக வைக்கிறது. உள்நுழையும்போது ஒருமுறை மட்டுமே அடையாளம் சரிபார்க்கப்படுகிறது; பதிவேட்டை அடையும் வாக்குச்சீட்டில் உங்கள் வாக்காளர் எண்ணின் மறைகுறியீடு மட்டுமே இருக்கும்.',
    aboutPoint1Title: 'கிளவுட் அணுகல்',
    aboutPoint1Copy: 'எந்தச் சாதனத்திலிருந்தும் அதே சரிபார்க்கப்பட்ட போர்டலை அணுகலாம்; நிறுவ எதுவும் இல்லை.',
    aboutPoint2Title: 'மாற்றம் தெரியும் பதிவேடு',
    aboutPoint2Copy:
      'ஒவ்வொரு வாக்குத் தொகுதியும் முந்தையதன் ஹாஷை உள்ளடக்கும்; பழைய வாக்கை மாற்றினால் அடுத்த அனைத்தும் உடைகிறது.',
    aboutPoint3Title: 'ஒரு வாக்காளர், ஒரு வாக்கு',
    aboutPoint3Copy: 'ஒரே வாக்காளரிடமிருந்து இரண்டாவது வாக்குச்சீட்டை பதிவேடு ஏற்காது.',
    aboutPoint4Title: 'திறந்த தணிக்கை',
    aboutPoint4Copy: 'முடிவுகள் பதிவேட்டிலிருந்தே மீண்டும் கணக்கிடப்படுகின்றன; யார் வேண்டுமானாலும் சரிபார்க்கலாம்.',

    contactTitle: 'தொடர்பு',
    contactSubtitle: 'பதிவு, வாக்குப்பதிவு அல்லது அணுகல் உதவிக்கு தேர்தல் உதவி மையத்தை அணுகவும்.',
    contactHelpline: 'வாக்காளர் உதவி எண்',
    contactEmail: 'மின்னஞ்சல்',
    contactAddress: 'அலுவலகம்',
    contactAddressValue: 'தேர்தல் சேவை மையம், நிர்வாசன் சதன், புது தில்லி 110001',
    contactHours: 'உதவி நேரம்',
    contactHoursValue: 'திங்கள் முதல் சனி வரை, காலை 9:00 - மாலை 6:00 IST',
    contactFormTitle: 'செய்தி அனுப்பு',
    yourName: 'உங்கள் பெயர்',
    yourEmail: 'உங்கள் மின்னஞ்சல்',
    yourMessage: 'செய்தி',
    sendMessage: 'செய்தியை அனுப்பு',
    messageSent: 'நன்றி. உங்கள் செய்தி தேர்தல் உதவி மையத்தை அடைந்துள்ளது.',

    ledgerStatus: 'பதிவேட்டு நிலை',
    ledgerVerifiedOk: 'சரிபார்க்கப்பட்டது — அனைத்து தொகுதிகளும் சரியாக இணைந்துள்ளன',
    ledgerBroken: 'பதிவேட்டில் மாற்றம் கண்டறியப்பட்டது',
    ledgerChecking: 'பதிவேடு சரிபார்க்கப்படுகிறது…',
    blocksSealedLabel: 'முத்திரையிட்ட தொகுதிகள்',
    ballotsOnLedger: 'பதிவேட்டில் உள்ள வாக்குகள்',
    reVerify: 'மீண்டும் சரிபார்',

    loginRequiredTitle: 'தொடர உள்நுழையவும்',
    loginRequiredCopy: 'வாக்காளர் எண்ணைச் சரிபார்த்த பிறகு வாக்களிக்கலாம்.',
    goToLogin: 'உள்நுழைவுக்குச் செல்',
    alreadyVotedNotice: 'உங்கள் வாக்கு ஏற்கனவே பதிவேட்டில் முத்திரையிடப்பட்டுள்ளது. நன்றி.',
    viewReceipt: 'ரசீதைப் பார்',
    viewResultsBtn: 'முடிவுகளைப் பார்',
    sealingBallot: 'உங்கள் வாக்கு பதிவேட்டில் முத்திரையிடப்படுகிறது…',
    voteSuccess: 'உங்கள் வாக்கு பிளாக்செயினில் பதிவு செய்யப்பட்டது.',

    footerTagline: 'கிளவுட் சார்ந்த, பிளாக்செயின் ஆதரவு தேர்தல் சேவை.',
    footerQuickLinks: 'விரைவு இணைப்புகள்',
    footerFollow: 'எங்களைத் தொடருங்கள்',
    socialNote: 'இந்த விளக்கப் போர்டலுக்கு இன்னும் அதிகாரப்பூர்வ சமூக ஊடகக் கணக்குகள் இல்லை.',
    footerContactUs: 'தொடர்பு கொள்ள',
    footerSupport: 'உதவி',
    footerLegal: 'இது ஒரு விளக்கப் போர்டல். வாக்காளர் பதிவுகள் உங்கள் உலாவியில் சேமிக்கப்படுகின்றன.',
    footerRights: 'கிளவுட் சார்ந்த பிளாக்செயின் மின்-வாக்கு அமைப்பு. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
  },

  hi: {
    siteBrand: 'क्लाउड आधारित ब्लॉकचेन ई-वोटिंग प्रणाली',
    siteBrandShort: 'ब्लॉकचेन ई-वोटिंग',
    menu: 'मेन्यू',
    closeMenu: 'मेन्यू बंद करें',
    navAboutSite: 'हमारे बारे में',
    navServicesSite: 'सेवाएं',
    navContact: 'संपर्क',
    loginRegister: 'लॉगिन / पंजीकरण',
    logout: 'लॉग आउट',
    myAccount: 'मेरा खाता',
    signedInAs: 'लॉगिन',
    welcomeUser: 'नमस्ते',

    menuVoterServices: 'मतदाता सेवाएं',
    menuElectionInfo: 'चुनाव जानकारी',
    dsRegisterRoll: 'मतदाता सूची में पंजीकरण',
    dsTrackStatus: 'आवेदन की स्थिति देखें',
    dsDownloadEpic: 'e-EPIC डाउनलोड करें',
    dsSearchRoll: 'मतदाता सूची में खोजें',
    dsFormsRegistration: 'पंजीकरण के फ़ॉर्म',
    dsPollingBooth: 'अपना मतदान केंद्र जानें',
    dsRegisterComplaint: 'शिकायत दर्ज करें',
    dsVoterEducation: 'मतदाता शिक्षा',
    eiCurrentElections: 'वर्तमान चुनाव',
    eiPastElections: 'पिछले चुनाव',
    eiTermHouses: 'सदनों का कार्यकाल',
    eiElectionResults: 'चुनाव परिणाम',
    eiElectoralRoll: 'मतदाता सूची',
    eiModelCode: 'आदर्श आचार संहिता',

    heroTitle: 'आपका वोट, आपकी आवाज़',
    heroTagline: 'सुरक्षित • पारदर्शी • विकेंद्रीकृत',
    heroSubtitle: 'ब्लॉकचेन संचालित ई-वोटिंग प्रणाली',
    heroCta: 'शुरू करें',
    heroNote: 'आपके वोट डालते ही हर मत एक छेड़छाड़-प्रमाण बहीखाते में दर्ज हो जाता है।',

    servicesHeading: 'हमारी सेवाएं',
    servicesSubheading: 'पंजीकरण से लेकर अंतिम गणना तक, मतदाता के लिए सब कुछ।',
    svcRegister: 'पंजीकरण',
    svcRegisterSub: 'नया मतदाता',
    svcLogin: 'लॉगिन',
    svcLoginSub: 'मौजूदा उपयोगकर्ता',
    svcCandidates: 'उम्मीदवार देखें',
    svcCandidatesSub: 'प्रोफ़ाइल और घोषणापत्र',
    svcCastVote: 'वोट डालें',
    svcCastVoteSub: 'सुरक्षित मतपत्र',
    svcResults: 'परिणाम देखें',
    svcResultsSub: 'लाइव सत्यापित गणना',

    checkHeading: 'अपना विवरण जांचें',
    checkSubheading: 'मतदाता पहचान संख्या या नाम से मतदाता सूची खोजें।',
    checkPlaceholder: 'मतदाता ID / नाम दर्ज करें',
    selectState: 'राज्य चुनें',
    allStates: 'सभी राज्य',
    search: 'खोजें',
    checkNoQuery: 'खोजने के लिए मतदाता ID या नाम दर्ज करें।',
    checkNoResults: 'कोई रिकॉर्ड नहीं मिला। वर्तनी जांचें या नए मतदाता के रूप में पंजीकरण करें।',
    checkFound: 'रिकॉर्ड मिले',
    colName: 'नाम',
    colVoterId: 'मतदाता ID',
    colState: 'राज्य',
    colBooth: 'मतदान केंद्र',
    colBallot: 'मत स्थिति',
    statusVoted: 'वोट दर्ज',
    statusNotVoted: 'अभी वोट नहीं डाला',
    checkPageTitle: 'मतदाता सूची में खोजें',
    checkPageSubtitle: 'अपनी प्रविष्टि, मतदान केंद्र और मत गिना गया या नहीं, यह जांचें।',

    aboutProjectTitle: 'परियोजना के बारे में',
    aboutProjectCopy:
      'निष्पक्ष चुनाव सुनिश्चित करने के लिए ब्लॉकचेन तकनीक पर आधारित एक सुरक्षित, पारदर्शी और छेड़छाड़-प्रमाण ई-वोटिंग प्रणाली।',
    learnMore: 'और जानें',

    newsHeading: 'नवीनतम अपडेट / समाचार',
    newsSubtitle: 'चुनाव हेल्पडेस्क की घोषणाएं।',
    newsPageTitle: 'अपडेट और समाचार',
    newsPageSubtitle: 'इस चुनाव के लिए प्रकाशित हर सूचना, नवीनतम पहले।',
    news1Title: 'चुनाव की तारीख घोषित',
    news1Date: '02 सित 2026',
    news1Copy: '15 अक्टूबर 2026 को प्रातः 7:00 से सायं 5:00 बजे तक मतदान होगा।',
    news2Title: 'नए मतदाता अब पंजीकरण कर सकते हैं',
    news2Date: '08 सित 2026',
    news2Copy: '30 सितंबर तक पंजीकरण खुला है। अपने EPIC नंबर के साथ पंजीकरण करें।',
    news3Title: '20 सितंबर को सिस्टम रखरखाव',
    news3Date: '15 सित 2026',
    news3Copy: 'बहीखाता नोड्स के उन्नयन के दौरान पोर्टल रात 1:00 से 3:00 बजे तक उपलब्ध नहीं रहेगा।',
    news4Title: 'उम्मीदवारों के घोषणापत्र प्रकाशित',
    news4Date: '18 सित 2026',
    news4Copy: 'चारों उम्मीदवारों की प्रोफ़ाइल और घोषणाएं अब उम्मीदवार पृष्ठ पर उपलब्ध हैं।',

    loginTitle: 'लॉगिन',
    loginSubtitle: 'अपनी मतदाता ID से साइन इन करके मतपत्र तक पहुंचें।',
    usernameLabel: 'मतदाता ID / उपयोगकर्ता नाम',
    passwordLabel: 'पासवर्ड',
    loginButton: 'लॉगिन',
    forgotPassword: 'पासवर्ड भूल गए?',
    or: 'अथवा',
    noAccount: 'खाता नहीं है?',
    registerLink: 'पंजीकरण करें',
    forgotHint: 'आपका पासवर्ड वही जन्मतिथि है जिससे आपने पंजीकरण किया (YYYY-MM-DD)। सहायता हेतु 1950 पर कॉल करें।',
    showPassword: 'पासवर्ड दिखाएं',
    hidePassword: 'पासवर्ड छिपाएं',
    demoCredentials: 'नमूना प्रमाण-पत्र',
    useThisId: 'यह ID उपयोग करें',

    registerTitle: 'अपना खाता बनाएं',
    registerSubtitle: 'चुनाव में भाग लेने के लिए अपना मतदाता खाता बनाएं।',
    fullNameLabel: 'पूरा नाम',
    fullNamePlaceholder: 'पूरा नाम',
    voterIdField: 'मतदाता ID',
    voterIdPlaceholderShort: 'मतदाता ID (EPIC संख्या)',
    dobLabel: 'जन्म तिथि',
    stateLabel: 'राज्य',
    emailLabel: 'ईमेल ID',
    mobileLabel: 'मोबाइल नंबर',
    createPassword: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    registerButton: 'पंजीकरण करें',
    haveAccount: 'पहले से खाता है?',
    loginLink: 'लॉगिन',
    registerSuccess: 'पंजीकरण पूर्ण। आप अब साइन इन हैं।',
    optional: 'वैकल्पिक',

    navDashboard: 'डैशबोर्ड',
    dashboardTitle: 'डैशबोर्ड',
    dashboardSubtitle: 'आपकी मतदाता सेवाएं एक नज़र में।',
    dashCardProfile: 'प्रोफ़ाइल',
    nextElection: 'अगला चुनाव',
    electionDateLabel: 'तिथि',
    electionTimeLabel: 'समय',
    electionDateValue: '15 अक्ट 2026',
    electionTimeValue: 'प्रातः 7:00 - सायं 5:00',
    ballotStatusLabel: 'मत स्थिति',
    dashQuickActions: 'त्वरित कार्य',
    dashYourBallot: 'आपका मत',
    dashBallotSub: 'मतदान यात्रा में आप कहां हैं।',
    stepRegistered: 'सूची में पंजीकृत',
    stepSignedIn: 'पहचान सत्यापित',
    stepBallotCast: 'मत बहीखाते पर सील',
    stepReceiptIssued: 'रसीद उपलब्ध',
    stepDone: 'पूर्ण',
    stepNow: 'अभी',
    stepNext: 'आगे',
    dashLiveResults: 'लाइव परिणाम',
    dashLedgerActivity: 'बहीखाता गतिविधि',

    profileTitle: 'प्रोफ़ाइल',
    profileSubtitle: 'मतदाता सूची में आपके लिए दर्ज विवरण।',
    downloadEpic: 'e-EPIC डाउनलोड करें',
    epicDownloaded: 'आपका e-EPIC डाउनलोड हो गया है।',
    accountStatus: 'खाता स्थिति',
    registeredOn: 'पंजीकरण तिथि',
    constituencyLabel: 'निर्वाचन क्षेत्र',
    boothLabel: 'मतदान केंद्र',
    contactDetails: 'संपर्क विवरण',
    notProvided: 'उपलब्ध नहीं',

    viewDetails: 'विवरण देखें',
    candidateProfile: 'उम्मीदवार प्रोफ़ाइल',
    manifestoLabel: 'घोषणापत्र',
    ballotNumberLabel: 'मतपत्र क्रमांक',
    closeLabel: 'बंद करें',
    voteForThis: 'इस उम्मीदवार को वोट दें',

    castYourVote: 'अपना वोट डालें',
    submitVote: 'वोट सबमिट करें',
    selectPrompt: 'एक उम्मीदवार चुनें और सबमिट करें। आपका मत बहीखाते पर सील कर दिया जाएगा।',

    voteCastTitle: 'आपका वोट दर्ज हो गया!',
    voteCastCopy: 'लोकतांत्रिक प्रक्रिया में भाग लेने के लिए धन्यवाद।',
    goToDashboard: 'डैशबोर्ड पर जाएं',

    winnerLabel: 'विजेता',
    electionResultsTitle: 'चुनाव परिणाम',

    electionInfoTitle: 'चुनाव जानकारी',
    electionInfoSubtitle: 'कार्यक्रम, पुराने रिकॉर्ड और इस चुनाव के नियम।',
    currentElectionHeading: 'वर्तमान चुनाव',
    pastElectionsHeading: 'पिछले चुनाव',
    termHousesHeading: 'सदनों का कार्यकाल',
    termHousesCopy:
      'निर्वाचित सदन अपनी पहली बैठक की तिथि से पांच वर्ष तक कार्य करता है। वर्तमान कार्यकाल 12 नवंबर 2021 को शुरू हुआ और 11 नवंबर 2026 को समाप्त होगा।',
    modelCodeHeading: 'आदर्श आचार संहिता',
    modelCodeCopy:
      'कार्यक्रम की घोषणा से परिणाम घोषित होने तक उम्मीदवार प्रचार में सार्वजनिक धन का उपयोग नहीं कर सकते, नई सार्वजनिक परियोजनाएं घोषित नहीं कर सकते, और मतदान केंद्र पर मतदाताओं से संपर्क नहीं कर सकते। शिकायतें संपर्क पृष्ठ से दर्ज की जा सकती हैं।',
    electoralRollHeading: 'मतदाता सूची',
    electoralRollCopy:
      'यह सूची इस चुनाव में मत देने के पात्र मतदाताओं की है। अपनी प्रविष्टि खोजें, मतदान केंद्र की पुष्टि करें और देखें कि आपका मत गिना गया या नहीं।',
    archiveGeneral: 'आम चुनाव',
    archiveAssembly: 'विधानसभा चुनाव',
    archiveBye: 'उपचुनाव',
    archiveCivic: 'नगर निकाय चुनाव',
    colElection: 'चुनाव',
    colPeriod: 'मतदान अवधि',
    colTurnoutHead: 'मतदान प्रतिशत',
    colOutcome: 'स्थिति',
    outcomeDeclared: 'परिणाम घोषित',
    outcomeOngoing: 'जारी है',
    seatsLabel: 'सीटें',
    candidatesLabel: 'उम्मीदवार',
    constituencyValue: 'महानगर वार्ड 07',

    aboutTitle: 'प्रणाली के बारे में',
    aboutSubtitle: 'क्लाउड पोर्टल और ब्लॉकचेन बहीखाता मिलकर चुनाव को ईमानदार कैसे रखते हैं।',
    aboutLead:
      'यह पोर्टल आपकी पहचान को आपके मत से अलग रखता है। पहचान केवल साइन-इन पर जांची जाती है; बहीखाते तक पहुंचने वाले मतपत्र में आपकी मतदाता ID का केवल एक साल्टेड डाइजेस्ट होता है।',
    aboutPoint1Title: 'क्लाउड आधारित पहुंच',
    aboutPoint1Copy: 'मतदाता किसी भी डिवाइस से उसी सत्यापित पोर्टल तक पहुंच सकते हैं, कुछ भी इंस्टॉल किए बिना।',
    aboutPoint2Title: 'छेड़छाड़-प्रमाण बहीखाता',
    aboutPoint2Copy: 'हर ब्लॉक पिछले ब्लॉक के हैश से जुड़ा है, इसलिए पुराना वोट बदलने पर आगे के सभी ब्लॉक टूट जाते हैं।',
    aboutPoint3Title: 'एक मतदाता, एक मत',
    aboutPoint3Copy: 'बहीखाता एक ही मतदाता से दूसरा मतपत्र अस्वीकार कर देता है।',
    aboutPoint4Title: 'खुली, लेखा-परीक्षण योग्य गणना',
    aboutPoint4Copy: 'परिणाम बहीखाते से ही दोबारा गिने जाते हैं और कोई भी सत्यापन दोहरा सकता है।',

    contactTitle: 'संपर्क',
    contactSubtitle: 'पंजीकरण, मतदान या सुगम्यता सहायता के लिए चुनाव हेल्पडेस्क से संपर्क करें।',
    contactHelpline: 'मतदाता हेल्पलाइन',
    contactEmail: 'ईमेल',
    contactAddress: 'कार्यालय',
    contactAddressValue: 'निर्वाचन सेवा केंद्र, निर्वाचन सदन, नई दिल्ली 110001',
    contactHours: 'सहायता समय',
    contactHoursValue: 'सोमवार से शनिवार, प्रातः 9:00 - सायं 6:00 IST',
    contactFormTitle: 'संदेश भेजें',
    yourName: 'आपका नाम',
    yourEmail: 'आपका ईमेल',
    yourMessage: 'संदेश',
    sendMessage: 'संदेश भेजें',
    messageSent: 'धन्यवाद। आपका संदेश चुनाव हेल्पडेस्क तक पहुंच गया है।',

    ledgerStatus: 'बहीखाता स्थिति',
    ledgerVerifiedOk: 'सत्यापित — सभी ब्लॉक सही ढंग से जुड़े हैं',
    ledgerBroken: 'बहीखाते में छेड़छाड़ पाई गई',
    ledgerChecking: 'बहीखाता सत्यापित किया जा रहा है…',
    blocksSealedLabel: 'सील किए गए ब्लॉक',
    ballotsOnLedger: 'बहीखाते पर मतपत्र',
    reVerify: 'पुनः सत्यापित करें',

    loginRequiredTitle: 'जारी रखने के लिए साइन इन करें',
    loginRequiredCopy: 'मतदाता ID सत्यापित करने के बाद वोट डालें।',
    goToLogin: 'लॉगिन पर जाएं',
    alreadyVotedNotice: 'आपका मत पहले ही बहीखाते पर सील हो चुका है। मतदान के लिए धन्यवाद।',
    viewReceipt: 'रसीद देखें',
    viewResultsBtn: 'परिणाम देखें',
    sealingBallot: 'आपका मतपत्र बहीखाते पर सील किया जा रहा है…',
    voteSuccess: 'आपका वोट ब्लॉकचेन पर दर्ज हो गया है।',

    footerTagline: 'क्लाउड आधारित, ब्लॉकचेन समर्थित चुनाव सेवा।',
    footerQuickLinks: 'त्वरित लिंक',
    footerFollow: 'हमें फ़ॉलो करें',
    socialNote: 'इस प्रदर्शन पोर्टल के अभी कोई आधिकारिक सोशल मीडिया खाते नहीं हैं।',
    footerContactUs: 'संपर्क करें',
    footerSupport: 'सहायता',
    footerLegal: 'यह एक प्रदर्शन पोर्टल है। मतदाता रिकॉर्ड आपके ब्राउज़र में संग्रहीत होते हैं।',
    footerRights: 'क्लाउड आधारित ब्लॉकचेन ई-वोटिंग प्रणाली। सर्वाधिकार सुरक्षित।',
  },
}
