// Strings for the console shell (navigation, header) and the ballot flow.
// Merged over ./translations and ./siteText; English is the fallback for any
// key a language does not define.

export const uiText = {
  en: {
    uiElections: 'Elections',
    uiCandidates: 'Candidates',
    uiCastVote: 'Cast Vote',
    uiResults: 'Results',
    uiMyReceipts: 'My Receipts',
    uiNotices: 'Notices',
    uiAdministration: 'Administration',
    uiElectionManagement: 'Election Management',
    uiCandidateVerification: 'Candidate Verification',
    uiVoterManagement: 'Voter Management',
    uiDepartments: 'Departments',
    uiAcademicYears: 'Academic Years',
    uiCommittees: 'Committees',
    uiReports: 'Reports',
    uiSystem: 'System',
    uiSettings: 'Settings',
    uiHelp: 'Help',
    uiProfile: 'Profile',
    uiMyElections: 'My Elections',
    uiNotifications: 'Notifications',
    uiLedger: 'Ledger',
    uiMainMenu: 'Main menu',
    uiLanguage: 'Language',
    uiAppearance: 'Appearance',
    uiOpenMenu: 'Open navigation menu',
    uiStudent: 'Student',
    uiAdmin: 'Administrator',

    uiStepSelect: 'Select candidate',
    uiStepReview: 'Review selection',
    uiStepConfirm: 'Confirm vote',
    uiStepReceipt: 'Receipt',
    uiConfidential: 'Your vote is confidential. Review your selection carefully before submitting.',
    uiContinue: 'Continue',
    uiYouSelected: 'You selected',
    uiChangeSelection: 'Change Selection',
    uiConfirmVote: 'Confirm Vote',
    uiCancel: 'Cancel',
    uiConfirmVoteCopy: 'You are about to submit your vote for {name}.',
    uiCannotChange: 'Once submitted, your vote cannot be changed.',
    uiSealing: 'Submitting your vote…',
    uiVoteRecorded: 'Your vote has been recorded',

    uiGoodMorning: 'Good morning',
    uiGoodAfternoon: 'Good afternoon',
    uiGoodEvening: 'Good evening',
  },

  ta: {
    uiElections: 'தேர்தல்கள்',
    uiCandidates: 'வேட்பாளர்கள்',
    uiCastVote: 'வாக்களி',
    uiResults: 'முடிவுகள்',
    uiMyReceipts: 'எனது ரசீதுகள்',
    uiNotices: 'அறிவிப்புகள்',
    uiAdministration: 'நிர்வாகம்',
    uiElectionManagement: 'தேர்தல் மேலாண்மை',
    uiCandidateVerification: 'வேட்பாளர் சரிபார்ப்பு',
    uiVoterManagement: 'வாக்காளர் மேலாண்மை',
    uiDepartments: 'துறைகள்',
    uiAcademicYears: 'கல்வி ஆண்டுகள்',
    uiCommittees: 'குழுக்கள்',
    uiReports: 'அறிக்கைகள்',
    uiSystem: 'அமைப்பு',
    uiSettings: 'அமைப்புகள்',
    uiHelp: 'உதவி',
    uiProfile: 'சுயவிவரம்',
    uiMyElections: 'எனது தேர்தல்கள்',
    uiNotifications: 'அறிவிப்புகள்',
    uiLedger: 'லெட்ஜர்',
    uiMainMenu: 'முதன்மை மெனு',
    uiLanguage: 'மொழி',
    uiAppearance: 'தோற்றம்',
    uiOpenMenu: 'மெனுவைத் திற',
    uiStudent: 'மாணவர்',
    uiAdmin: 'நிர்வாகி',

    uiStepSelect: 'வேட்பாளரைத் தேர்ந்தெடு',
    uiStepReview: 'தேர்வை சரிபார்',
    uiStepConfirm: 'வாக்கை உறுதிசெய்',
    uiStepReceipt: 'ரசீது',
    uiConfidential: 'உங்கள் வாக்கு ரகசியமானது. சமர்ப்பிக்கும் முன் உங்கள் தேர்வை கவனமாகச் சரிபார்க்கவும்.',
    uiContinue: 'தொடரவும்',
    uiYouSelected: 'நீங்கள் தேர்ந்தெடுத்தது',
    uiChangeSelection: 'தேர்வை மாற்று',
    uiConfirmVote: 'வாக்கை உறுதிசெய்',
    uiCancel: 'ரத்து செய்',
    uiConfirmVoteCopy: 'நீங்கள் {name} அவர்களுக்கு உங்கள் வாக்கைச் சமர்ப்பிக்க உள்ளீர்கள்.',
    uiCannotChange: 'சமர்ப்பித்த பின் உங்கள் வாக்கை மாற்ற முடியாது.',
    uiSealing: 'உங்கள் வாக்கு சமர்ப்பிக்கப்படுகிறது…',
    uiVoteRecorded: 'உங்கள் வாக்கு பதிவு செய்யப்பட்டது',

    uiGoodMorning: 'காலை வணக்கம்',
    uiGoodAfternoon: 'மதிய வணக்கம்',
    uiGoodEvening: 'மாலை வணக்கம்',
  },

  hi: {
    uiElections: 'चुनाव',
    uiCandidates: 'उम्मीदवार',
    uiCastVote: 'मतदान करें',
    uiResults: 'परिणाम',
    uiMyReceipts: 'मेरी रसीदें',
    uiNotices: 'सूचनाएं',
    uiAdministration: 'प्रशासन',
    uiElectionManagement: 'चुनाव प्रबंधन',
    uiCandidateVerification: 'उम्मीदवार सत्यापन',
    uiVoterManagement: 'मतदाता प्रबंधन',
    uiDepartments: 'विभाग',
    uiAcademicYears: 'शैक्षणिक वर्ष',
    uiCommittees: 'समितियां',
    uiReports: 'रिपोर्ट',
    uiSystem: 'सिस्टम',
    uiSettings: 'सेटिंग्स',
    uiHelp: 'सहायता',
    uiProfile: 'प्रोफ़ाइल',
    uiMyElections: 'मेरे चुनाव',
    uiNotifications: 'अधिसूचनाएं',
    uiLedger: 'लेजर',
    uiMainMenu: 'मुख्य मेनू',
    uiLanguage: 'भाषा',
    uiAppearance: 'रूप',
    uiOpenMenu: 'मेनू खोलें',
    uiStudent: 'छात्र',
    uiAdmin: 'प्रशासक',

    uiStepSelect: 'उम्मीदवार चुनें',
    uiStepReview: 'चयन की समीक्षा',
    uiStepConfirm: 'वोट की पुष्टि',
    uiStepReceipt: 'रसीद',
    uiConfidential: 'आपका वोट गोपनीय है। सबमिट करने से पहले अपना चयन ध्यान से जांचें।',
    uiContinue: 'जारी रखें',
    uiYouSelected: 'आपने चुना',
    uiChangeSelection: 'चयन बदलें',
    uiConfirmVote: 'वोट की पुष्टि करें',
    uiCancel: 'रद्द करें',
    uiConfirmVoteCopy: 'आप {name} के लिए अपना वोट सबमिट करने वाले हैं।',
    uiCannotChange: 'सबमिट करने के बाद आपका वोट बदला नहीं जा सकता।',
    uiSealing: 'आपका वोट सबमिट हो रहा है…',
    uiVoteRecorded: 'आपका वोट दर्ज हो गया है',

    uiGoodMorning: 'सुप्रभात',
    uiGoodAfternoon: 'नमस्कार',
    uiGoodEvening: 'शुभ संध्या',
  },
}
